kind: Secret
apiVersion: v1
metadata:
  name: database-secret
  namespace: tarroja
data:
  mariadb_root_password: NEd0ZSEzT3YzalFNCg==
  mariadb_database: dGFycm9qYV9saWZldHJhY2sK
  mariadb_user: anVhbml0b3RycmoK
  mariadb_password: M202aCpwTVkK
type: Opaque
