kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: fc-api-hpa
  namespace: tarroja
  labels:
    app: fc-api
spec:
  scaleTargetRef:
    kind: Deployment
    name: fc-api
    apiVersion: extensions/v1beta1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 100
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 100
