apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-api-deployment
  labels:
    app: fc-api
  namespace: tarroja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-api
  template:
    metadata:
      labels:
        app: fc-api
    spec:
      containers:
      - name: fc-api
        image: juanitotrrj/fc-api:latest
        ports:
        - containerPort: 80
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fc-api
        type: microservice
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            defaultMode: 420
        - name: phpfpm-config-volume
          configMap:
            name: phpfpm-config
            defaultMode: 420
        - name: fc-api-env
          secret:
            secretName: fc-api-env
            defaultMode: 420
      containers:
        - name: fc-api
          image: juanitotrrj/fc-api:latest
          command:
            - php-fpm
          ports:
            - name: phpfpm
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 180Mi
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/lifetrack
            - name: fc-api-env
              mountPath: /var/www/lifetrack/.env
              subPath: .env
            - name: phpfpm-config-volume
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 40
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - cp -rp /app/. /var/www/lifetrack
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: nginx
          image: 'nginx:1.17.0-alpine'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/lifetrack
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /nginx_status
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /nginx_status
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
