apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tarroja
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: tarroja
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: juanitotrrj/mariadb:10.5
        imagePullPolicy: Always
        name: mysql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mariadb_root_password
        - name: MARIADB_DATABASE
          value: tarroja_lifetrack
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mariadb_user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mariadb_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
