kind: Service
apiVersion: v1
metadata:
  name: fc-api
  namespace: tarroja
  labels:
    app: fc-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31325
  selector:
    app: fc-api
  type: LoadBalancer
  sessionAffinity: None
status:
  loadBalancer: {}
