apiVersion: v1
kind: Service
metadata:
  labels:
    app: fc-client
  name: fc-client
  namespace: tarroja
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31326
  selector:
    app: fc-client
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
